### ISSUE TITLE
Add json output to the rest of the rhm commands

### ISSUE THREAD

**Issue by maleck13** [feedhenry/rhm#28]
We have added a flag to allow specifying the output type 

```
-o=json

```
Currently only a couple of commands use this flag. We should add it to the rest
see https://github.com/feedhenry/rhm/blob/master/commands/get/projects.go#L66 for example

**Comment by philbrookes** [comment]
@maleck13 Yeah cool, assign this issue to me, I'll get started this evening.

**Comment by philbrookes** [comment]
PR #29
